// Dark mode ready: uses Tailwind dark: classes throughout.
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ColorModeProvider } from "@/context/ColorModeContext";
import ColorModeToggle from "@/components/ColorModeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <ColorModeProvider>
          <div className="flex min-h-screen">
            <aside className="w-64 bg-gray-100 dark:bg-gray-900 p-6 border-r border-gray-200 dark:border-gray-700">
              <nav className="space-y-4">
                <div>
                  <a href="/" className="block text-lg font-bold text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400">Chat</a>
                </div>
                <div>
                  <p className="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Database</p>
                  <ul className="ml-2 mt-2 space-y-4">
                    <li>
                      <p className="text-xs font-semibold text-gray-900 dark:text-white uppercase tracking-wide mb-1">Lineage Views</p>
                      <ul className="ml-4 space-y-2">
                        <li>
                          <a href="/database/lineage" className="block text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400">Full Lineage</a>
                        </li>
                        <li>
                          <a href="/database/stage-to-bronze" className="block text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400">Stage &#8594; Bronze</a>
                        </li>
                        <li>
                          <a href="/database/bronze-to-silver" className="block text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400">Bronze &#8594; Silver</a>
                        </li>
                        <li>
                          <a href="/database/silver-to-gold" className="block text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400">Silver &#8594; Gold</a>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <p className="text-xs font-semibold text-gray-900 dark:text-white uppercase tracking-wide mb-1">Reference Tables</p>
                      <ul className="ml-4 space-y-2">
                        <li>
                          <a href="/database/silver-gold-tables" className="block text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400">Silver &#8594; Gold</a>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <p className="text-xs font-semibold text-gray-900 dark:text-white uppercase tracking-wide mb-1">Procedures</p>
                      <ul className="ml-4 space-y-2">
                        <li>
                          <a href="/database/silver-gold-procs" className="block text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400">Bronze &#8594; Silver &#8594; Gold</a>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <p className="text-xs font-semibold text-gray-900 dark:text-white uppercase tracking-wide mb-1">Admin</p>
                      <ul className="ml-4 space-y-2">
                        <li>
                          <a href="/database/admin" className="block text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400">Admin</a>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </nav>
            </aside>
            <main className="flex-1 p-8 bg-gray-100 dark:bg-gray-900">
              {children}
            </main>
          </div>
        </ColorModeProvider>
      </body>
    </html>
  );
}
